spring:
  data:
    elasticsearch:
      cluster-name: docker-cluster
      #必须和ES服务器配置文件config\elasticsearch.yml中的cluster.name一致
      cluster-nodes: 192.168.1.8:19300
      repositories:
        enabled: true
server:
  port: 14500