server:
  port: 8080
spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.1.7:3306/mytest?useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull
    username: xhsit
    password: sit1818
    driver-class-name: com.mysql.jdbc.Driver
  cache:
    type: redis
  redis:
    database: 1
    host: 192.168.1.7
    port: 6379
  data:
    elasticsearch:
      cluster-name: docker-cluster
      cluster-nodes: 192.168.1.8:9300
      repositories:
        enabled: true

mybatis:
  type-aliases-package: com.github.davidji80.springboot.mybatis.model
  mapper-locations: classpath:mapping/**/*.xml